version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0-browsers
    working_directory: ~/repo/directory-tree
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - browser-tools/install-browser-tools
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: gradle check
      - run: gradle jacocoTestReport
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml

workflows:
  test:
    jobs:
      - build
